defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 127.0.0.1

development:
  <<: *defaults
  database: hr_development
  username: postgres
  password:

test:
  <<: *defaults
  database: hr_test
  username: postgres
  password:

production:
  <<: *defaults
  database: web
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
